Support Node 10 (again) (#11)
When I removed Node 10 support in #2, I didn't know that Azure Pipelines
tasks run on Node 10. The reason I haven't noticed that this library
doesn't work in tasks is that it was originally written for use not in
tasks, but in scripts (see e.g. the built-in `ShellScript` task), where
the Node version can be chosen by the pipeline author.

## About the diff

Without `allowSyntheticDefaultImports`, `npm run build` fails:

    error TS1259: Module '"/[…]/azure-pipelines-logging/node_modules/@types/array.prototype.flatmap/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

Without `esModuleInterop`, `npm test` fails:

    TypeError: array_prototype_flatmap_1.default is not a function

With `"lib": [ "esnext" ]`, using standard library features from ES
versions newer than ES2018 (such as `Array.prototype.flatMap`) isn't a
compile-time error, even though it is a run-time error in Node 10. We
could remove the `lib` compiler option altogether (in which case it
would be implicitly set based on the value of the `target` option), but
then someone might add e.g. `"lib": [ "esnext" ]` later without
realizing said implication of doing so. This is a typical situation
where I prefer explicitness over brevity.